# Generated by Django 4.1.5 on 2023-01-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="contact", field=models.CharField(max_length=10),
        ),
    ]
